species:
  composition_fuel: 'H2:1'                    #Fuel composition
  composition_oxidizer: 'O2:0.21, N2:0.79'    #Oxydizer composition


geometry:
  width: 0.1                                  #Nozzle distance (m)

properties:
  fuel_temperature: 300.0                     #Fuel Temperature  (K)
  oxidizer_temperature: 300.0                 #Oxydizer Temperature (K)
  pressure: 103235                            #Pressure (Pa)

debits:
  min_fuel: 0.01                               #Surface mass flow rate (kg/m^2/s)
  max_fuel: 0.60                               
  nb_points_fuel: 30                           #Number of presolution points between min and max 
  min_oxidizer: 2.0
  max_oxidizer: 3
  nb_points_oxidizer: 1

path:
  output_folder: 'H2AIR_DATA_30FUEL'



